
import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import Stripe from 'https://esm.sh/stripe@14.21.0';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.0';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Create Supabase client for user authentication
    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_ANON_KEY') ?? '',
    );

    // Get the user from the authorization header
    const authHeader = req.headers.get('Authorization')!;
    const token = authHeader.replace('Bearer ', '');
    const { data: { user } } = await supabaseClient.auth.getUser(token);

    if (!user) {
      throw new Error('Not authenticated');
    }

    const email = user.email;
    if (!email) {
      throw new Error('User email not found');
    }

    const stripe = new Stripe(Deno.env.get('STRIPE_SECRET_KEY') || '', {
      apiVersion: '2023-10-16',
    });

    // Check if customer exists
    const customers = await stripe.customers.list({
      email: email,
      limit: 1
    });

    if (customers.data.length === 0) {
      return new Response(
        JSON.stringify({ 
          status: 'no_subscription',
          hasActiveSubscription: false,
          remainingOneTimeCredits: 0
        }),
        {
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
          status: 200,
        }
      );
    }

    const customerId = customers.data[0].id;
    
    // Check for active subscriptions (both monthly and yearly)
    const subscriptions = await stripe.subscriptions.list({
      customer: customerId,
      status: 'active',
      limit: 100
    });

    const hasActiveSubscription = subscriptions.data.length > 0;
    
    // Get one-time payment information - only count successful charges
    const charges = await stripe.charges.list({
      customer: customerId,
      limit: 100
    });
    
    // For simplicity, each successful one-time payment gives 30 credits
    // Only count charges that were successful (paid status)
    const successfulOneTimePayments = charges.data.filter(
      charge => charge.status === 'succeeded' && 
                charge.amount_captured > 0 && 
                !charge.disputed && 
                !charge.refunded
    ).length;
    
    const totalOneTimeCredits = successfulOneTimePayments * 30;
    
    // Count all user stories generated by this user
    const { data: userStories, error } = await supabaseClient
      .from('user_stories')
      .select('*', { count: 'exact' })
      .eq('user_id', user.id);
    
    if (error) {
      console.error('Error fetching user stories:', error);
      throw error;
    }
    
    // Calculate used credits
    const totalUsage = userStories?.length || 0;
    
    // Calculate how many of the one-time credits have been used
    // If user has active subscription, they don't use one-time credits
    // If no active subscription, they use free credits first (5), then one-time credits
    let usedOneTimeCredits = 0;
    
    if (!hasActiveSubscription) {
      // If they've used more than the free tier (5), the excess counts against one-time credits
      usedOneTimeCredits = Math.max(0, totalUsage - 5);
    }
    
    const remainingOneTimeCredits = Math.max(0, totalOneTimeCredits - usedOneTimeCredits);

    console.log(`User: ${email}, Active subscription: ${hasActiveSubscription}, One-time credits: ${remainingOneTimeCredits}, Total usage: ${totalUsage}, Used one-time: ${usedOneTimeCredits}, Total one-time purchased: ${totalOneTimeCredits}`);

    return new Response(
      JSON.stringify({ 
        status: hasActiveSubscription ? 'subscribed' : 'not_subscribed',
        hasActiveSubscription,
        remainingOneTimeCredits
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200,
      }
    );
  } catch (error) {
    console.error('Error checking subscription status:', error);
    return new Response(
      JSON.stringify({ error: error.message }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 500,
      }
    );
  }
});
